networks:
    default:
        name: my-network
services:
    web:
        image: 53jk1/pythonftw:0.0.3
        command: python app.py
        ports:
            - "5000:5000"
        networks:
            - default
        volumes:
            - .:/code